const SUPPORTED_MEMORY_GAME_TYPES = ['werewolf', 'debate'] as const;

/** 单个玩家累积摘要的字符上限 */
const SUMMARY_CHAR_LIMIT = 800;
/** 单次对局观察文本的字符上限 */
const OBSERVATION_CHAR_LIMIT = 300;
/** 注入 prompt 时整体关系记忆的字符上限 */
const RELATIONSHIP_PROMPT_CHAR_LIMIT = 1500;
/** 共同参与多少局后开始注入记忆 */
const MEMORY_INJECTION_THRESHOLD = 1;

const SESSION_RECENT_MESSAGE_LIMIT = 24;
const SESSION_SUMMARY_CHAR_LIMIT = 1600;

export {
  SUPPORTED_MEMORY_GAME_TYPES,
  SUMMARY_CHAR_LIMIT,
  OBSERVATION_CHAR_LIMIT,
  RELATIONSHIP_PROMPT_CHAR_LIMIT,
  MEMORY_INJECTION_THRESHOLD,
  SESSION_RECENT_MESSAGE_LIMIT,
  SESSION_SUMMARY_CHAR_LIMIT,
};
