const SUPPORTED_MEMORY_GAME_TYPES = ['werewolf', 'debate'] as const;
const RELATIONSHIP_PROMPT_CHAR_LIMIT = 1200;
const RELATIONSHIP_ENTRY_CHAR_LIMIT = 100;
const SESSION_RECENT_MESSAGE_LIMIT = 24;
const SESSION_SUMMARY_CHAR_LIMIT = 1600;

export {
  SUPPORTED_MEMORY_GAME_TYPES,
  RELATIONSHIP_PROMPT_CHAR_LIMIT,
  RELATIONSHIP_ENTRY_CHAR_LIMIT,
  SESSION_RECENT_MESSAGE_LIMIT,
  SESSION_SUMMARY_CHAR_LIMIT,
};
