const WEREWOLF = {
  MAX_DAYS: 5,
  SPEECH_ACK_TIMEOUT_MS: 120000,
  MAX_AGENT_FALLBACK_RETRIES: 2,
  SPEECH_CHAR_LIMIT: 120,
  MIN_PLAYERS: 12
};

const DEBATE = {
  SPEECH_ACK_TIMEOUT_MS: 120000,
  MIN_PLAYERS: 8,
  MAX_PLAYERS: 12,
  PRO_COUNT: 4,
  CON_COUNT: 4,
  MAX_JUDGES: 4
};

module.exports = { WEREWOLF, DEBATE };
