CREATE TABLE skins (
  id text PRIMARY KEY,
  name text NOT NULL,
  version text NOT NULL DEFAULT 'v3.2',
  source text NOT NULL DEFAULT 'admin',
  terms_json jsonb NOT NULL,
  background text NOT NULL,
  truth text NOT NULL DEFAULT '',
  clues_json jsonb NOT NULL,
  noises_json jsonb NOT NULL,
  memory_examples_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  enabled integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE model_providers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  base_url text NOT NULL DEFAULT '',
  api_format text NOT NULL DEFAULT 'openai-compatible',
  api_key_cipher text NOT NULL DEFAULT '',
  api_key_iv text NOT NULL DEFAULT '',
  api_key_tag text NOT NULL DEFAULT '',
  enabled integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE models (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_id bigint REFERENCES model_providers(id) ON DELETE RESTRICT,
  provider text NOT NULL,
  name text NOT NULL,
  display_name text NOT NULL DEFAULT '',
  base_url text NOT NULL DEFAULT '',
  api_format text NOT NULL DEFAULT 'openai-compatible',
  api_key_cipher text NOT NULL DEFAULT '',
  api_key_iv text NOT NULL DEFAULT '',
  api_key_tag text NOT NULL DEFAULT '',
  enabled integer NOT NULL DEFAULT 1,
  thinking_enabled integer NOT NULL DEFAULT 0,
  disabled_reason text,
  disabled_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE voice_packages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  provider text NOT NULL DEFAULT 'browser',
  voice_id text NOT NULL DEFAULT '',
  language text NOT NULL DEFAULT 'zh-CN',
  gender text NOT NULL DEFAULT '',
  style text NOT NULL DEFAULT '',
  rate text NOT NULL DEFAULT '0%',
  pitch text NOT NULL DEFAULT '0%',
  sample_text text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  temperature double precision NOT NULL DEFAULT 0.85,
  enabled integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE players (
  id bigint PRIMARY KEY,
  nickname text NOT NULL,
  name text NOT NULL DEFAULT '',
  avatar text NOT NULL DEFAULT '',
  sex text NOT NULL DEFAULT '未知',
  personality text NOT NULL DEFAULT '',
  provider text NOT NULL DEFAULT 'deepseek',
  model text NOT NULL DEFAULT 'deepseek-v4-pro',
  model_id bigint REFERENCES models(id) ON DELETE SET NULL,
  fallback_model_id bigint REFERENCES models(id) ON DELETE SET NULL,
  voice_package_id bigint REFERENCES voice_packages(id) ON DELETE SET NULL,
  temperature double precision NOT NULL DEFAULT 0.85,
  enabled integer NOT NULL DEFAULT 1,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE werewolf_modes (
  id text PRIMARY KEY,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  roles_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  rules_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  sheriff_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  win_condition text NOT NULL DEFAULT 'side',
  enabled integer NOT NULL DEFAULT 1,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE werewolf_roles (
  id text PRIMARY KEY,
  name text NOT NULL,
  faction text NOT NULL DEFAULT 'good',
  role_type text NOT NULL DEFAULT 'villager',
  responsibility text NOT NULL DEFAULT '',
  ability text NOT NULL DEFAULT '',
  play_style_advice text NOT NULL DEFAULT '',
  key_info text NOT NULL DEFAULT '',
  rule_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  enabled integer NOT NULL DEFAULT 1,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE app_settings (
  key text PRIMARY KEY,
  value_json jsonb NOT NULL DEFAULT 'null'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE admin_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  display_name text NOT NULL DEFAULT '',
  enabled integer NOT NULL DEFAULT 1,
  must_change_password integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE games (
  id text PRIMARY KEY,
  game_type text NOT NULL DEFAULT 'werewolf',
  mode text NOT NULL,
  skin_id text REFERENCES skins(id) ON DELETE SET NULL,
  skin_name text NOT NULL DEFAULT '',
  winner text,
  win_reason text NOT NULL DEFAULT '',
  topic_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  players_json jsonb NOT NULL,
  rounds_json jsonb NOT NULL,
  event_json jsonb NOT NULL,
  audio_resources_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_games_type_created ON games(game_type, created_at DESC);

CREATE TABLE game_players (
  game_id text NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  player_id bigint NOT NULL REFERENCES players(id) ON DELETE RESTRICT,
  player_snapshot_json jsonb NOT NULL,
  PRIMARY KEY (game_id, player_id)
);

CREATE TABLE game_playback_events (
  game_id text NOT NULL REFERENCES games(id) ON DELETE CASCADE,
  sequence integer NOT NULL,
  protocol_version integer NOT NULL,
  event_type text NOT NULL,
  view_mode text NOT NULL,
  payload_json jsonb NOT NULL,
  media_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (game_id, sequence)
);
CREATE INDEX idx_game_playback_events_game ON game_playback_events(game_id, sequence);

CREATE TABLE game_player_selections (
  game_type text PRIMARY KEY,
  player_ids_json jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE player_game_memories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_type text NOT NULL,
  owner_player_id bigint NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  subject_player_id bigint NOT NULL REFERENCES players(id) ON DELETE CASCADE,
  games_played integer NOT NULL DEFAULT 0,
  familiarity_score double precision NOT NULL DEFAULT 0,
  traits_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  recent_summary text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(game_type, owner_player_id, subject_player_id)
);
CREATE INDEX idx_player_game_memories_lookup
  ON player_game_memories(game_type, owner_player_id, games_played DESC, familiarity_score DESC);

CREATE TABLE matches (
  id text PRIMARY KEY,
  game_type text NOT NULL,
  workflow_id text NOT NULL,
  status text NOT NULL DEFAULT 'running',
  current_step_index integer NOT NULL DEFAULT 0,
  version integer NOT NULL DEFAULT 0,
  config_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  state_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  blockers_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  error_json jsonb NOT NULL DEFAULT 'null'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);

CREATE TABLE match_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id text NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  version integer NOT NULL,
  status text NOT NULL,
  current_step_index integer NOT NULL,
  last_event_seq integer,
  state_json jsonb NOT NULL,
  blockers_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_match_snapshots_match ON match_snapshots(match_id, version DESC);

CREATE TABLE workflow_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id text NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  seq integer NOT NULL,
  type text NOT NULL,
  step_id text,
  player_id text,
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  visibility text NOT NULL DEFAULT 'public',
  visible_to_player_ids_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  idempotency_key text,
  channel text NOT NULL DEFAULT 'public',
  scope_key text,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(match_id, seq),
  UNIQUE(match_id, idempotency_key)
);
CREATE INDEX idx_workflow_events_match_seq ON workflow_events(match_id, seq);
CREATE INDEX idx_workflow_events_type ON workflow_events(type);
CREATE INDEX idx_workflow_events_channel ON workflow_events(match_id, channel);
CREATE INDEX idx_workflow_events_scope ON workflow_events(match_id, channel, scope_key);

CREATE TABLE pending_actions (
  id text PRIMARY KEY,
  match_id text NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  step_id text NOT NULL,
  epoch_id text,
  player_id text,
  actor_type text NOT NULL,
  action_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  result_event_seq integer,
  idempotency_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(match_id, idempotency_key)
);
CREATE INDEX idx_pending_actions_match ON pending_actions(match_id, status);

CREATE TABLE ai_tasks (
  id text PRIMARY KEY,
  match_id text NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  step_id text NOT NULL,
  task_key text NOT NULL,
  epoch_id text,
  player_id text,
  action text NOT NULL,
  status text NOT NULL DEFAULT 'queued',
  prompt_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  context_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  raw_output text NOT NULL DEFAULT '',
  result_json jsonb NOT NULL DEFAULT 'null'::jsonb,
  error_json jsonb NOT NULL DEFAULT 'null'::jsonb,
  attempts integer NOT NULL DEFAULT 0,
  visible_event_seq_max integer NOT NULL DEFAULT 0,
  visible_event_ids_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  worker_id text NOT NULL DEFAULT '',
  claimed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(match_id, step_id, task_key)
);
CREATE INDEX idx_ai_tasks_match_status ON ai_tasks(match_id, status);

CREATE TABLE outbox_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id text NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  event_seq integer NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(match_id, event_seq)
);
CREATE INDEX idx_outbox_match_status ON outbox_messages(match_id, status);

CREATE TABLE memory_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id text NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  scope text NOT NULL DEFAULT 'public',
  owner_id text,
  snapshot_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_event_seq integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_memory_snapshots_match ON memory_snapshots(match_id, scope, owner_id);

CREATE TABLE action_window_epochs (
  id text PRIMARY KEY,
  match_id text NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  step_id text NOT NULL,
  action_type text NOT NULL,
  status text NOT NULL DEFAULT 'open',
  window_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_event_seq integer,
  resolved_event_seq integer,
  expires_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(match_id, step_id, action_type)
);
CREATE INDEX idx_action_window_epochs_match ON action_window_epochs(match_id, status);

CREATE TABLE workflow_effects (
  id text PRIMARY KEY,
  match_id text NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  step_id text,
  source_event_seq integer,
  effect_type text NOT NULL,
  status text NOT NULL DEFAULT 'proposed',
  priority integer NOT NULL DEFAULT 0,
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  applied_event_seq integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_workflow_effects_match ON workflow_effects(match_id, status);
CREATE INDEX idx_workflow_effects_type ON workflow_effects(effect_type);

CREATE TABLE workflow_interrupts (
  id text PRIMARY KEY,
  match_id text NOT NULL REFERENCES matches(id) ON DELETE CASCADE,
  step_id text,
  effect_id text REFERENCES workflow_effects(id) ON DELETE SET NULL,
  interrupt_type text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  priority integer NOT NULL DEFAULT 0,
  payload_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  resolution_json jsonb NOT NULL DEFAULT 'null'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_workflow_interrupts_match ON workflow_interrupts(match_id, status);

CREATE TABLE game_traces (
  id text PRIMARY KEY,
  game_type text NOT NULL,
  game_mode text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'recording',
  llm_call_count integer NOT NULL DEFAULT 0,
  agent_decision_count integer NOT NULL DEFAULT 0,
  event_count integer NOT NULL DEFAULT 0,
  error_message text,
  participants_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL,
  completed_at timestamptz,
  duration_ms integer
);

CREATE TABLE trace_spans (
  id text PRIMARY KEY,
  trace_id text NOT NULL REFERENCES game_traces(id) ON DELETE CASCADE,
  parent_span_id text,
  span_type text NOT NULL,
  span_name text NOT NULL,
  start_time timestamptz NOT NULL,
  end_time timestamptz,
  status text NOT NULL DEFAULT 'ok',
  attributes_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  error_json jsonb,
  created_at timestamptz NOT NULL
);
CREATE INDEX idx_spans_trace ON trace_spans(trace_id);
CREATE INDEX idx_spans_parent ON trace_spans(parent_span_id);

CREATE TABLE llm_records (
  id text PRIMARY KEY,
  trace_id text NOT NULL REFERENCES game_traces(id) ON DELETE CASCADE,
  span_id text,
  game_type text NOT NULL,
  provider text NOT NULL,
  model text NOT NULL,
  api_format text NOT NULL,
  player_id bigint,
  player_role text,
  player_faction text,
  messages_json jsonb NOT NULL,
  response_text text NOT NULL DEFAULT '',
  thinking_text text,
  temperature double precision,
  max_tokens integer,
  prompt_tokens integer,
  completion_tokens integer,
  latency_ms integer NOT NULL,
  status text NOT NULL DEFAULT 'success',
  error_message text,
  created_at timestamptz NOT NULL
);
CREATE INDEX idx_llm_trace ON llm_records(trace_id);
CREATE INDEX idx_llm_player ON llm_records(trace_id, player_id);

CREATE TABLE agent_decisions (
  id text PRIMARY KEY,
  trace_id text NOT NULL REFERENCES game_traces(id) ON DELETE CASCADE,
  span_id text,
  game_type text NOT NULL,
  player_id bigint NOT NULL,
  player_role text,
  player_faction text,
  decision_type text NOT NULL,
  phase text,
  day integer,
  prompt_text text,
  response_text text,
  chosen_target bigint,
  fallback_used integer NOT NULL DEFAULT 0,
  fallback_reason text,
  skill_id text,
  created_at timestamptz NOT NULL
);
CREATE INDEX idx_decisions_trace ON agent_decisions(trace_id);
CREATE INDEX idx_decisions_player ON agent_decisions(trace_id, player_id);
CREATE INDEX idx_decisions_type ON agent_decisions(decision_type);

CREATE TABLE game_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trace_id text NOT NULL REFERENCES game_traces(id) ON DELETE CASCADE,
  span_id text,
  event_type text NOT NULL,
  phase text,
  day integer,
  event_json jsonb NOT NULL,
  received_at timestamptz NOT NULL
);
CREATE INDEX idx_events_trace ON game_events(trace_id);
CREATE INDEX idx_events_type ON game_events(event_type);

CREATE TABLE state_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trace_id text NOT NULL REFERENCES game_traces(id) ON DELETE CASCADE,
  checkpoint text NOT NULL,
  day integer,
  phase text,
  player_count integer,
  alive_count integer,
  snapshot_json jsonb NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE INDEX idx_snapshots_trace ON state_snapshots(trace_id);
CREATE INDEX idx_snapshots_checkpoint ON state_snapshots(trace_id, checkpoint);
