ALTER TABLE matches ADD COLUMN definition_version text;
UPDATE matches
SET definition_version = COALESCE(NULLIF(config_json ->> 'gameDefinitionVersion', ''), '1.0.0');
ALTER TABLE matches ALTER COLUMN definition_version SET NOT NULL;
ALTER TABLE matches ALTER COLUMN definition_version SET DEFAULT '1.0.0';
ALTER TABLE matches ADD COLUMN state_schema_version integer NOT NULL DEFAULT 1;
ALTER TABLE matches ADD CONSTRAINT matches_state_schema_version_positive
  CHECK (state_schema_version > 0);
ALTER TABLE matches ADD CONSTRAINT matches_status_valid
  CHECK (status IN ('running', 'waiting', 'completed', 'failed', 'paused_debug'));
ALTER TABLE matches ADD CONSTRAINT matches_completion_timestamp_valid
  CHECK (status <> 'completed' OR completed_at IS NOT NULL);

ALTER TABLE match_snapshots ADD COLUMN state_schema_version integer NOT NULL DEFAULT 1;
ALTER TABLE match_snapshots ADD CONSTRAINT match_snapshots_state_schema_version_positive
  CHECK (state_schema_version > 0);

ALTER TABLE workflow_events ADD COLUMN event_schema_version integer NOT NULL DEFAULT 1;
ALTER TABLE workflow_events ADD COLUMN actor_type text NOT NULL DEFAULT 'player';
ALTER TABLE workflow_events ADD COLUMN causation_id text;
ALTER TABLE workflow_events ADD COLUMN correlation_id text;
UPDATE workflow_events
SET actor_type = CASE
  WHEN player_id IS NULL AND channel = 'system' THEN 'system'
  WHEN player_id IS NULL THEN 'unknown'
  ELSE 'player'
END;
ALTER TABLE workflow_events ADD CONSTRAINT workflow_events_schema_version_positive
  CHECK (event_schema_version > 0);
ALTER TABLE workflow_events ADD CONSTRAINT workflow_events_channel_valid
  CHECK (channel IN ('public', 'system', 'scope'));

ALTER TABLE games ADD COLUMN definition_version text NOT NULL DEFAULT '1.0.0';
ALTER TABLE games ADD COLUMN snapshot_schema_version integer NOT NULL DEFAULT 1;
ALTER TABLE games ADD COLUMN variant_key text;
ALTER TABLE games ADD COLUMN variant_revision integer;
ALTER TABLE games ADD COLUMN variant_snapshot_json jsonb NOT NULL DEFAULT '{}'::jsonb;
UPDATE games SET variant_key = NULLIF(mode, ''), variant_revision = 1 WHERE mode <> '';
ALTER TABLE games ADD CONSTRAINT games_snapshot_schema_version_positive
  CHECK (snapshot_schema_version > 0);
ALTER TABLE games ADD CONSTRAINT games_variant_revision_positive
  CHECK (variant_revision IS NULL OR variant_revision > 0);
ALTER TABLE games ADD CONSTRAINT games_variant_snapshot_object
  CHECK (jsonb_typeof(variant_snapshot_json) = 'object');

ALTER TABLE ai_tasks ADD COLUMN max_attempts integer NOT NULL DEFAULT 3;
ALTER TABLE ai_tasks ADD COLUMN claim_expires_at timestamptz;
ALTER TABLE ai_tasks ADD COLUMN next_attempt_at timestamptz;
ALTER TABLE ai_tasks ADD CONSTRAINT ai_tasks_attempts_nonnegative CHECK (attempts >= 0);
ALTER TABLE ai_tasks ADD CONSTRAINT ai_tasks_max_attempts_positive CHECK (max_attempts > 0);
ALTER TABLE ai_tasks ADD CONSTRAINT ai_tasks_status_valid
  CHECK (status IN ('queued', 'retrying', 'running', 'succeeded', 'failed', 'cancelled'));

ALTER TABLE outbox_messages ADD COLUMN attempts integer NOT NULL DEFAULT 0;
ALTER TABLE outbox_messages ADD COLUMN worker_id text NOT NULL DEFAULT '';
ALTER TABLE outbox_messages ADD COLUMN claim_expires_at timestamptz;
ALTER TABLE outbox_messages ADD COLUMN next_attempt_at timestamptz;
ALTER TABLE outbox_messages ADD COLUMN error_json jsonb NOT NULL DEFAULT 'null'::jsonb;
ALTER TABLE outbox_messages ADD COLUMN sent_at timestamptz;
ALTER TABLE outbox_messages ADD CONSTRAINT outbox_attempts_nonnegative CHECK (attempts >= 0);
ALTER TABLE outbox_messages ADD CONSTRAINT outbox_status_valid
  CHECK (status IN ('pending', 'sending', 'sent', 'failed'));
ALTER TABLE outbox_messages ADD CONSTRAINT outbox_event_fkey
  FOREIGN KEY (match_id, event_seq)
  REFERENCES workflow_events(match_id, seq)
  ON DELETE CASCADE;

ALTER TABLE model_providers ADD COLUMN credential_ref text;
ALTER TABLE model_providers ADD COLUMN encryption_key_version text;

CREATE TABLE game_variants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  game_type text NOT NULL,
  variant_key text NOT NULL,
  definition_version text NOT NULL,
  name text NOT NULL,
  description text NOT NULL DEFAULT '',
  config_schema_version integer NOT NULL DEFAULT 1,
  config_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  enabled boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  revision integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (game_type, variant_key),
  CHECK (config_schema_version > 0),
  CHECK (revision > 0),
  CHECK (jsonb_typeof(config_json) = 'object')
);

CREATE TABLE admin_audit_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_admin_id bigint REFERENCES admin_users(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  request_id text NOT NULL,
  before_json jsonb NOT NULL DEFAULT 'null'::jsonb,
  after_json jsonb NOT NULL DEFAULT 'null'::jsonb,
  ip_address inet,
  user_agent text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (length(action) > 0),
  CHECK (length(entity_type) > 0),
  CHECK (length(request_id) > 0)
);

DROP INDEX idx_game_playback_events_game;
DROP INDEX idx_workflow_events_match_seq;

CREATE INDEX idx_games_created ON games(created_at DESC);
CREATE INDEX idx_games_skin ON games(skin_id) WHERE skin_id IS NOT NULL;
CREATE INDEX idx_game_players_player ON game_players(player_id, game_id);
CREATE INDEX idx_models_provider_updated ON models(provider_id, updated_at DESC);
CREATE INDEX idx_matches_active_updated
  ON matches(updated_at, id) WHERE status IN ('running', 'waiting');
CREATE INDEX idx_matches_terminal_created
  ON matches(created_at DESC, id) WHERE status IN ('completed', 'failed', 'paused_debug');
CREATE INDEX idx_ai_tasks_claimable
  ON ai_tasks(next_attempt_at, created_at, id)
  WHERE status IN ('queued', 'retrying');
CREATE INDEX idx_ai_tasks_expired_claim
  ON ai_tasks(claim_expires_at, id) WHERE status = 'running';
CREATE INDEX idx_outbox_claimable
  ON outbox_messages(match_id, next_attempt_at, id) WHERE status = 'pending';
CREATE INDEX idx_outbox_expired_claim
  ON outbox_messages(claim_expires_at, id) WHERE status = 'sending';
CREATE INDEX idx_game_traces_created ON game_traces(created_at DESC);
CREATE INDEX idx_game_traces_filter ON game_traces(game_type, status, created_at DESC);
CREATE INDEX idx_trace_spans_game_id
  ON trace_spans ((attributes_json ->> 'game.id'))
  WHERE parent_span_id IS NULL AND attributes_json ? 'game.id';
CREATE INDEX idx_game_variants_list
  ON game_variants(game_type, enabled, sort_order, variant_key);
CREATE INDEX idx_admin_audit_created ON admin_audit_log(created_at DESC, id DESC);
CREATE INDEX idx_admin_audit_entity
  ON admin_audit_log(entity_type, entity_id, created_at DESC);
