/**
 * 频道映射常量
 * 行动类型 → 作用域 和 角色 → 作用域 的映射
 * 全局唯一来源，消除 actionChannel.ts / gameEventBuilder.ts / channelRouter.ts 中的重复
 */

/** 行动类型 → 作用域 scopeKey */
export const SCOPE_ACTION_MAP: Record<string, string> = {
  wolf_kill: 'wolves',
  wolf_speech: 'wolves',
  wolf_vote: 'wolves',
  seer_check: 'seer',
  guard_protect: 'guard',
  witch_save: 'witch',
  witch_poison: 'witch',
  hybrid_choose_master: 'hybrid',
  elder_silence: 'silence_elder',
  butterfly_hug: 'butterfly',
  stalker_assassinate: 'stalker',
  wolf_beauty_charm: 'wolf_beauty',
  demon_inspect: 'demon',
  nightmare_fear: 'nightmare',
  magician_swap: 'magician',
  fortune_teller_mark: 'fortune_teller',
  big_bad_wolf_kill: 'wolves',
  crow_curse: 'crow',
  black_merchant_gift: 'black_merchant',
  younger_brother_kill: 'wolves',
  ghost_bride_link: 'ghost_bride',
  ghost_bride_chat: 'ghost_bride',
  ghost_bride_kill: 'ghost_bride',
  demon_hunter_hunt: 'demon_hunter',
  spirit_wolf_learn: 'spirit_wolf',
  spirit_wolf_inspect: 'spirit_wolf',
  spirit_wolf_guard: 'spirit_wolf',
  spirit_wolf_antidote: 'spirit_wolf',
  wolf_witch_curse: 'wolves',
  illusionist_illusion: 'illusionist',
  penguin_freeze: 'penguin',
  fox_inspect: 'fox',
  bear_tamer_roar: 'bear_tamer',
  escape_hunter_speech: 'escape_hunters',
  escape_hunter_vote: 'escape_hunters',
};

/** 角色 → 作用域 scopeKey */
export const ROLE_CHANNEL_MAP: Record<string, string> = {
  werewolf: 'wolves',
  white_wolf_king: 'wolves',
  wolf_king: 'wolves',
  wolf_elder_brother: 'wolves',
  wolf_younger_brother: 'wolves',
  seer: 'seer',
  guard: 'guard',
  witch: 'witch',
  hybrid: 'hybrid',
  silence_elder: 'silence_elder',
  butterfly: 'butterfly',
  stalker: 'stalker',
  wolf_beauty: 'wolf_beauty',
  demon: 'demon',
  nightmare: 'nightmare',
  magician: 'magician',
  big_bad_wolf: 'wolves',
  fortune_teller: 'fortune_teller',
  hidden_wolf: 'wolves',
  crow: 'crow',
  black_merchant: 'black_merchant',
  ghost_bride: 'ghost_bride',
  demon_hunter: 'demon_hunter',
  magic_wolf: 'wolves',
  spirit_wolf: 'wolves',
  wolf_witch: 'wolves',
  illusionist: 'illusionist',
  penguin: 'penguin',
  fox: 'fox',
  bear_tamer: 'bear_tamer',
  escape_hunter: 'escape_hunters',
};
