#!/bin/sh
set -eu

case "${OPS_SIGNAL:-}" in
  TERM) kill -TERM "$$" ;;
  INT) kill -INT "$$" ;;
  WAIT)
    trap 'exit 143' TERM
    trap 'exit 130' INT
    printf 'ready\n'
    while :; do sleep 1 & wait "$!"; done
    ;;
  *) exit 97 ;;
esac
